server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    怎么获得系统的密码
    password: ${DB_PASSWORD}

  cache:
    type: redis
  redis:
    host: 192.168.239.100
    port: 6379
    password: ${DB_PASSWORD}
    cache-null-values: true  #当找不到数据时，缓存一个null值
    time-to-live: 120000   #设置键值对的过期时间
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        timeout: 10000
      database: 0


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lab.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
